# Form implementation generated from reading ui file 'gui-interes-compuesto.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lbOrincipal = QtWidgets.QLabel(parent=self.centralwidget)
        self.lbOrincipal.setGeometry(QtCore.QRect(20, 30, 71, 16))
        self.lbOrincipal.setObjectName("lbOrincipal")
        self.lbTasaanual = QtWidgets.QLabel(parent=self.centralwidget)
        self.lbTasaanual.setGeometry(QtCore.QRect(20, 70, 47, 13))
        self.lbTasaanual.setObjectName("lbTasaanual")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 120, 47, 13))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 170, 47, 13))
        self.label_4.setObjectName("label_4")
        self.principal_input = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.principal_input.setGeometry(QtCore.QRect(100, 30, 113, 20))
        self.principal_input.setObjectName("principal_input")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(130, 210, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.tasa_input = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.tasa_input.setGeometry(QtCore.QRect(100, 70, 113, 20))
        self.tasa_input.setObjectName("tasa_input")
        self.tiempo_input = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.tiempo_input.setGeometry(QtCore.QRect(100, 120, 113, 20))
        self.tiempo_input.setObjectName("tiempo_input")
        self.periodos_input = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.periodos_input.setGeometry(QtCore.QRect(100, 160, 113, 20))
        self.periodos_input.setObjectName("periodos_input")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(parent=self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAbrir = QtGui.QAction(parent=MainWindow)
        self.actionAbrir.setObjectName("actionAbrir")
        self.actionSalir = QtGui.QAction(parent=MainWindow)
        self.actionSalir.setObjectName("actionSalir")
        self.menuFile.addAction(self.actionAbrir)
        self.menuFile.addAction(self.actionSalir)
        self.menuFile.addSeparator()
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Cálculo del interpes compuesto"))
        self.lbOrincipal.setText(_translate("MainWindow", "Principal (P)"))
        self.lbTasaanual.setText(_translate("MainWindow", "Tasa anuak (r)"))
        self.label_3.setText(_translate("MainWindow", "TextLabel"))
        self.label_4.setText(_translate("MainWindow", "TextLabel"))
        self.principal_input.setText(_translate("MainWindow", "0"))
        self.pushButton.setText(_translate("MainWindow", "PushButton"))
        self.tasa_input.setText(_translate("MainWindow", "0"))
        self.tiempo_input.setText(_translate("MainWindow", "0"))
        self.periodos_input.setText(_translate("MainWindow", "0"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionAbrir.setText(_translate("MainWindow", "Abrir"))
        self.actionSalir.setText(_translate("MainWindow", "Salir"))
